### ISSUE TITLE
Doesn't update already installed app

### ISSUE THREAD

**Issue by gorru** [SamVerschueren/gulp-adb-install#1]
Hi.
I tried with the true option
`.pipe(adbInstall(true))`
 but it fails 
`Failure [INSTALL_FAILED_ALREADY_EXISTS]`

**Comment by SamVerschueren** [comment]
You have to use an options object.

```js
.pipe(adbInstall({replace: true}))
```

**Comment by gorru** [comment]
You are obviously right. I read the readme too fast.
It works.
Thanks

**Comment by SamVerschueren** [comment]
No problem, glad it works :)
